space= input("경기장은 어디입니까?")
winner = input("이긴팀은 어디입니까?")
loser = input("진팀은 어디입니까?")
mvp = input("우수선수는 누구입니까?")
score = input("스코어은 얼마입니까?")

print("\n오늘", space, "에서 야구경기가 열렸습니다")
print(winner,"와",loser,"는 치열한 공방전을 펼쳤습니다")
print(mvp,"가 맹활활약을 하였습니다")
print("결국",winner,"이",loser,"를 ", score,"로 이겼습니다")
